/**
 * Maps IANA timezone (from Intl.DateTimeFormat) to ISO 3166-1 alpha-2 country code.
 * Used for Stripe Connect account creation. Covers common timezones; unmapped ones return undefined.
 */
const TIMEZONE_TO_COUNTRY: Record<string, string> = {
  // US
  "America/New_York": "US",
  "America/Los_Angeles": "US",
  "America/Chicago": "US",
  "America/Denver": "US",
  "America/Phoenix": "US",
  "America/Anchorage": "US",
  "America/Honolulu": "US",
  "America/Detroit": "US",
  "America/Boise": "US",
  "America/Indianapolis": "US",
  "America/Kentucky/Louisville": "US",
  "America/Kentucky/Monticello": "US",
  "America/North_Dakota/Center": "US",
  "America/North_Dakota/New_Salem": "US",
  "America/North_Dakota/Beulah": "US",
  "America/Indiana/Indianapolis": "US",
  "America/Indiana/Vincennes": "US",
  "America/Indiana/Winamac": "US",
  "America/Indiana/Tell_City": "US",
  "America/Indiana/Knox": "US",
  "America/Indiana/Petersburg": "US",
  "America/Indiana/Marengo": "US",
  "America/Indiana/Vevay": "US",
  "America/Indiana/Martinsville": "US",
  "America/Juneau": "US",
  "America/Sitka": "US",
  "America/Metlakatla": "US",
  "America/Yakutat": "US",
  "America/Nome": "US",
  "America/Adak": "US",
  "America/Atka": "US",
  "Pacific/Honolulu": "US",
  "US/Pacific": "US",
  "US/Mountain": "US",
  "US/Central": "US",
  "US/Eastern": "US",
  "US/Alaska": "US",
  "US/Hawaii": "US",
  "US/Arizona": "US",
  // Canada
  "America/Toronto": "CA",
  "America/Vancouver": "CA",
  "America/Edmonton": "CA",
  "America/Winnipeg": "CA",
  "America/Halifax": "CA",
  "America/St_Johns": "CA",
  "America/Regina": "CA",
  "America/Moncton": "CA",
  "America/Glace_Bay": "CA",
  "America/Goose_Bay": "CA",
  "America/Blanc-Sablon": "CA",
  "America/Montreal": "CA",
  "America/Nipigon": "CA",
  "America/Thunder_Bay": "CA",
  "America/Iqaluit": "CA",
  "America/Pangnirtung": "CA",
  "America/Atikokan": "CA",
  "America/Rainy_River": "CA",
  "America/Resolute": "CA",
  "America/Rankin_Inlet": "CA",
  "America/Inuvik": "CA",
  "America/Dawson_Creek": "CA",
  "America/Fort_Nelson": "CA",
  "America/Creston": "CA",
  "America/Dawson": "CA",
  "America/Whitehorse": "CA",
  "Canada/Pacific": "CA",
  "Canada/Mountain": "CA",
  "Canada/Central": "CA",
  "Canada/Eastern": "CA",
  "Canada/Atlantic": "CA",
  "Canada/Newfoundland": "CA",
  // India
  "Asia/Kolkata": "IN",
  "Asia/Calcutta": "IN",
  // UK
  "Europe/London": "GB",
  "GB": "GB",
  "GB-Eire": "GB",
  // Australia
  "Australia/Sydney": "AU",
  "Australia/Melbourne": "AU",
  "Australia/Perth": "AU",
  "Australia/Brisbane": "AU",
  "Australia/Adelaide": "AU",
  "Australia/Darwin": "AU",
  "Australia/Hobart": "AU",
  "Australia/Canberra": "AU",
  "Australia/Lord_Howe": "AU",
  "Australia/Eucla": "AU",
  // UAE
  "Asia/Dubai": "AE",
  // Japan
  "Asia/Tokyo": "JP",
  "Japan": "JP",
  // China
  "Asia/Shanghai": "CN",
  "Asia/Hong_Kong": "HK",
  "Asia/Chongqing": "CN",
  "Asia/Harbin": "CN",
  "Asia/Urumqi": "CN",
  "PRC": "CN",
  // Europe
  "Europe/Berlin": "DE",
  "Europe/Paris": "FR",
  "Europe/Amsterdam": "NL",
  "Europe/Brussels": "BE",
  "Europe/Madrid": "ES",
  "Europe/Rome": "IT",
  "Europe/Zurich": "CH",
  "Europe/Vienna": "AT",
  "Europe/Stockholm": "SE",
  "Europe/Oslo": "NO",
  "Europe/Copenhagen": "DK",
  "Europe/Helsinki": "FI",
  "Europe/Dublin": "IE",
  "Europe/Lisbon": "PT",
  "Europe/Warsaw": "PL",
  "Europe/Prague": "CZ",
  "Europe/Budapest": "HU",
  "Europe/Bucharest": "RO",
  "Europe/Athens": "GR",
  "Europe/Istanbul": "TR",
  "Europe/Moscow": "RU",
  "Europe/Kiev": "UA",
  "Europe/Kyiv": "UA",
  // Middle East
  "Asia/Riyadh": "SA",
  "Asia/Jerusalem": "IL",
  "Asia/Tehran": "IR",
  "Asia/Baghdad": "IQ",
  "Asia/Kuwait": "KW",
  "Asia/Bahrain": "BH",
  "Asia/Qatar": "QA",
  "Asia/Muscat": "OM",
  // Southeast Asia
  "Asia/Singapore": "SG",
  "Asia/Bangkok": "TH",
  "Asia/Jakarta": "ID",
  "Asia/Manila": "PH",
  "Asia/Kuala_Lumpur": "MY",
  "Asia/Ho_Chi_Minh": "VN",
  "Asia/Saigon": "VN",
  // Africa
  "Africa/Cairo": "EG",
  "Africa/Johannesburg": "ZA",
  "Africa/Lagos": "NG",
  "Africa/Nairobi": "KE",
  "Africa/Casablanca": "MA",
  // South America
  "America/Sao_Paulo": "BR",
  "America/Buenos_Aires": "AR",
  "America/Santiago": "CL",
  "America/Bogota": "CO",
  "America/Lima": "PE",
  "America/Mexico_City": "MX",
  "America/Cancun": "MX",
  "America/Monterrey": "MX",
  "America/Tijuana": "MX",
  "America/Chihuahua": "MX",
  "America/Mazatlan": "MX",
  "America/Hermosillo": "MX",
  "America/Merida": "MX",
  "America/Guadalajara": "MX",
  "America/Matamoros": "MX",
  "America/Ojinaga": "MX",
  "America/Bahia_Banderas": "MX",
  // New Zealand
  "Pacific/Auckland": "NZ",
  "NZ": "NZ",
  // UTC/Etc - don't map; let server use IP/headers
};

/**
 * Get country code from system timezone (Intl.DateTimeFormat).
 * Returns undefined if timezone cannot be mapped.
 */
export function getCountryFromTimezone(): string | undefined {
  if (typeof Intl === "undefined" || !Intl.DateTimeFormat) return undefined;
  try {
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
    if (!tz) return undefined;
    return TIMEZONE_TO_COUNTRY[tz];
  } catch {
    return undefined;
  }
}
